import { createStoryManifest } from './league.js';
import { affordable, assertAccounting, decide, digest, fee, holdings, initialize, isFighter, prepareRound, primaryAsk, roundPriorities, satisfaction, schedule, settleRound } from './engine.js';
import { characterRoll, personalityOf, traderPersonalities } from './personalities.js';
                                                                              

                                                    
export const campaigns={spotlight:{cost:120,duration:2,reach:3,boost:400,label:'Window spotlight'},value:{cost:180,duration:2,reach:4,boost:600,label:'Fair-price promise'},hype:{cost:250,duration:2,reach:4,boost:1000,label:'Prestige parade'}};
                                                                                                                                                                                                                         
                                                                                                                                               
                                                                                                                                                 
                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                            
const cast=['Jinx','Draven','Ornn','Ahri','Garen','Teemo','Veigar','Ashe'];
export function bazaarManifest(seed=42)          {
 const m=createStoryManifest(seed),c=m.config; m.engineVersion='4.0.0';
 c.archetypes=cast.map(id=>c.archetypes.find(a=>a.champion===id) );
 // A compact pool covers physical, magical, defensive and movement demand.
 const ids=['3006','3047','3111','3031','3072','3085','3094','3089','3135','3157','3115','3083','3075','3065'];
 c.items=c.items.filter(i=>ids.includes(i.id.replace('lol-','')));
 for(const a of c.archetypes){const ranked=c.items.map(i=>({i,score:i.features.reduce((n,f,d)=>n+a.weights[d]*10*Math.log(1+f/10),0)/i.reference})).sort((a,b)=>b.score-a.score||a.i.id.localeCompare(b.i.id));a.shoppingList=[ranked[0].i.id,...ranked.filter(x=>x.i.id!==ranked[0].i.id&&(!x.i.boots||!ranked[0].i.boots)).slice(0,2).map(x=>x.i.id)];}
 Object.assign(c,{bazaar:true,rounds:10,valueFighters:0,fixedFighters:8,valueTraders:4,momentumTraders:0,fighterCash:4200,traderCash:12000,income:650,incomeRounds:10,slots:3,initialStock:2,maxStock:3,productionEvery:3,inventoryCap:8,perItemCap:2});
 c.league .waves=1;c.league .waveEvery=100;c.story .traders=[{...traderPersonalities[2],id:'player',label:'Your shop'},...structuredClone(traderPersonalities.slice(0,3))];return m;
}
export function startBazaar(seed=42,mode               ='shop')        {
 const state=initialize(bazaarManifest(seed));for(const a of state.agents.filter(isFighter))a.name=state.manifest.config.archetypes[a.archetype].name;
 const b       ={state,mode,phase:'decisions',player:'value-trader-1',actions:[],listings:{},bids:{},offers:[],npc:[],relationships:{},promotions:[],advertising:{},advertisingTreasury:0,report:[],history:[],startCash:12000};for(const a of state.agents.filter(isFighter))for(const m of state.agents.filter(a=>!isFighter(a)))relationship(b,a.id,m.id);openDay(b);return b;
}
export const merchant=(b       ,id=b.player)=>b.state.agents.find(a=>a.id===id) ;
export function relationship(b       ,customer       ,seller       )              {return b.relationships[`${customer}:${seller}`]??={purchases:0,paid:0,rejections:0,abandoned:0,trust:0,preference:0,exposures:0};}
function note(b       ,text       ){b.report.push(text);b.history.push({day:b.state.round,text});b.state.events.push({round:b.state.round,type:'bazaar-consequence',data:{text}});}
export function need(b       ,a      ){if(a.equipped.length>=3)return undefined;return b.state.manifest.config.archetypes[a.archetype].shoppingList.find(id=>!a.equipped.includes(id));}
export function customerLimit(b       ,a      ,seller       ,item       ){const s=b.state,i=s.manifest.config.items.find(i=>i.id===item) ,p=personalityOf(s,a) ,r=relationship(b,a.id,seller);const gain=satisfaction(s,a,item)-satisfaction(s,a);const base=Math.min(Math.floor(i.reference*p.maxPayBps/10000),Math.floor(gain*s.manifest.config.willingness*(1+p.prestigeBps/20000)));let boost=0;for(const ad of b.promotions.filter(x=>x.merchant===seller&&x.item===item&&x.start<=s.round&&x.end>=s.round&&x.customers.includes(a.id)))boost=Math.max(boost,Math.floor(campaigns[ad.kind].boost*(.25+(p.impulseBps+p.prestigeBps)/24000)*Math.max(.25,1+r.trust/10)));boost=Math.min(1000,boost);return affordable(a.cash,s.buyerFeeBps,Math.min(i.reference*s.manifest.config.priceCap,Math.floor(base*(1+boost/10000))));}
const order=(b       ,owner       ,item       ,side              ,price       ,text       ,counterparty        )      =>({id:`${b.state.round}:${owner}:${side}:${item}`,owner,item,side,price,priority:roundPriorities(b.state).get(owner) ,reason:{rule:'bazaar-order',text,inputs:{}},...(counterparty?{counterparty}:{})});
function openDay(b       ){prepareRound(b.state);b.phase='decisions';b.report=[];b.listings={};b.bids={};b.offers=[];
 const s=b.state,pr=roundPriorities(s);b.npc=s.agents.filter(a=>!isFighter(a)&&(b.mode==='spectate'||a.id!==b.player)).flatMap(a=>decide(s,a,pr.get(a.id) ));
 // NPC listings cover owned inventory, using each merchant's existing exit rule.
 for(const a of s.agents.filter(a=>!isFighter(a)&&(b.mode==='spectate'||a.id!==b.player))){const p=personalityOf(s,a) ;for(const i of s.manifest.config.items.filter(i=>a.inventory[i.id].length&&!b.npc.some(o=>o.owner===a.id&&o.item===i.id&&o.side==='ask'))){const cost=a.inventory[i.id][0].cost,age=s.round-a.inventory[i.id][0].round;let price=Math.ceil(i.reference*(p.mode==='bargain'?Math.max(.7,1.12-age*.08):1.4-age*.045));if(p.mode==='bagholder')price=Math.max(price,Math.ceil(cost*10000/(10000-s.sellerFeeBps)));b.npc.push(order(b,a.id,i.id,'ask',price,`${p.sell} Inventory age ${age} days.`));}
 if(s.round%3===2&&holdings(a)>0&&characterRoll(s.manifest.seed,`ad:${s.round}:${a.id}`)<.65){const item=s.manifest.config.items.find(i=>a.inventory[i.id].length) ;promote(b,a.id,item.id,p.mode==='bagholder'?'hype':p.mode==='bargain'?'value':'spotlight');}}
 for(const a of s.agents.filter(isFighter)){const id=need(b,a);if(!id)continue;const i=s.manifest.config.items.find(i=>i.id===id) ,cap=customerLimit(b,a,b.player,id);b.offers.push({customer:a.id,item:id,price:Math.max(1,Math.min(cap,Math.floor(i.reference*(.95+characterRoll(s.manifest.seed,`quote:${s.round}:${a.id}`)*.15)))),attempts:0,status:'open'});}
 note(b,`Day ${s.round} opens: ${b.offers.length} customers still shopping. Wholesale supply is finite; accepted negotiations compete at settlement.`);assertBazaar(b);
}
function promote(b       ,seller       ,item       ,kind             ){const a=merchant(b,seller),c=campaigns[kind];if(!c||a.cash<c.cost||!a.inventory[item]?.length)throw Error('Campaign requires owned inventory and enough unreserved cash.');if(b.promotions.some(p=>p.merchant===seller&&p.end>=b.state.round))throw Error('Only one active campaign per merchant.');a.cash-=c.cost;b.advertisingTreasury+=c.cost;b.state.shop+=c.cost;b.advertising[seller]=(b.advertising[seller]??0)+c.cost;const customers=b.state.agents.filter(a=>isFighter(a)&&need(b,a)===item).sort((a,c)=>characterRoll(b.state.manifest.seed,`reach:${b.state.round}:${seller}:${a.id}`)-characterRoll(b.state.manifest.seed,`reach:${b.state.round}:${seller}:${c.id}`)).slice(0,c.reach).map(a=>a.id);b.promotions.push({merchant:seller,item,kind,start:b.state.round,end:b.state.round+c.duration-1,customers,sales:0});for(const id of customers)relationship(b,id,seller).exposures++;note(b,`${a.name} spent ${c.cost} g on ${c.label}; reached ${customers.length} relevant customers for ${c.duration} days. Paid advertising, not newspaper reporting.`);}
export function reservations(b       ){const a=merchant(b),cash=Object.values(b.bids).reduce((n,p)=>n+p+fee(p,b.state.buyerFeeBps),0),copies=new Set(b.offers.filter(o=>o.status==='accepted').map(o=>o.item));return {cash,available:a.cash-cash,copies};}
export function act(b       ,input                           ){if((b.mode!=='shop'&&input.kind!=='intervention')||b.phase!=='decisions')throw Error('Shop actions require the decisions phase.');const action       ={...structuredClone(input),day:b.state.round,phase:'decisions'},a=merchant(b),i=b.state.manifest.config.items.find(i=>i.id===input.item);
 if(['bid','list','counter'].includes(input.kind)&&(!Number.isSafeInteger(input.price)||input.price <(input.kind==='counter'?1:0)||input.price >(i?.reference??b.state.manifest.config.items.find(x=>x.id===b.offers.find(o=>o.customer===input.customer)?.item)?.reference??0)*4))throw Error('Enter an integer price within the scenario cap.');
 if(input.kind==='bid'){if(!i)throw Error('Unknown item.');const old=b.bids[i.id];if(input.price===0)delete b.bids[i.id];else b.bids[i.id]=input.price ;if(reservations(b).available<0||Object.keys(b.bids).length+holdings(a)>8||Object.keys(b.bids).some(id=>a.inventory[id].length>=2)){if(old===undefined)delete b.bids[i.id];else b.bids[i.id]=old;throw Error('Bid reservations exceed cash or inventory capacity. Sale proceeds cannot fund bids.');}}
 else if(input.kind==='list'){if(!i||!a.inventory[i.id].length)throw Error('You must own the copy.');if(reservations(b).copies.has(i.id))throw Error('This copy is reserved for negotiation; reject it before relisting.');if(input.price===0)delete b.listings[i.id];else b.listings[i.id]=input.price ;}
 else if(['accept','counter','reject'].includes(input.kind)){const o=b.offers.find(o=>o.customer===input.customer);if(!o||o.status==='rejected'||o.status==='abandoned')throw Error('Offer expired or closed.');if(o.status==='accepted'&&input.kind!=='reject')throw Error('Reject to release this reservation first.');if(input.kind==='reject'){o.status='rejected';const r=relationship(b,o.customer,b.player);r.rejections++;r.preference=Math.max(-5,r.preference-1);note(b,`${b.state.agents.find(a=>a.id===o.customer) .name}: your shop declined the negotiation; merchant preference decreased by 1 (bounded). No purchase was promised.`);}else{if(!a.inventory[o.item].length||b.offers.some(x=>x!==o&&x.item===o.item&&x.status==='accepted'))throw Error('No unreserved owned copy.');const customer=b.state.agents.find(a=>a.id===o.customer) ,p=personalityOf(b.state,customer) ;if(o.attempts>=Math.min(2,Math.max(1,Math.ceil(p.patience/5))))throw Error('Negotiation attempts exhausted.');o.attempts++;const price=input.kind==='accept'?o.price:input.price ;if(price<1)throw Error('Counteroffer must be positive.');if(price>customerLimit(b,customer,b.player,o.item)){o.status=o.attempts>=Math.min(2,Math.max(1,Math.ceil(p.patience/5)))?'abandoned':'open';const r=relationship(b,o.customer,b.player);if(o.status==='abandoned'){r.abandoned++;r.preference=Math.max(-5,r.preference-1);}note(b,`${customer.name} declined your ${price} g counteroffer because it exceeded their limit${o.status==='abandoned'?'; they walked away':'; one final proposal may remain'}.`);}else{o.status='accepted';o.agreed=price;delete b.listings[o.item];note(b,`${customer.name} provisionally accepted ${price} g. Copy reserved; cheaper acceptable rivals can still win at settlement.`);}}}
 else if(input.kind==='advertise'){const cost=campaigns[input.campaign ]?.cost;if(!cost||reservations(b).available<cost)throw Error('Campaign exceeds unreserved cash.');promote(b,b.player,input.item ,input.campaign );}
 else if(input.kind==='intervention'){schedule(b.state,input.intervention );note(b,'Developer intervention recorded. This run is assisted, outside normal shop actions.');}
 else throw Error('Unknown action.');b.actions.push(action);b.state.events.push({round:b.state.round,type:'player-action',data:{action}});assertBazaar(b);
}
export function settleDay(b       ){if(b.phase!=='decisions')throw Error('Day is not open.');const s=b.state,orders=[...b.npc];if(b.mode==='shop'){for(const [id,p] of Object.entries(b.bids))orders.push(order(b,b.player,id,'bid',p,'Player wholesale bid; original cash reserved.','shop'));for(const [id,p] of Object.entries(b.listings))orders.push(order(b,b.player,id,'ask',p,'Player retail listing.'));for(const o of b.offers.filter(o=>o.status==='accepted'))orders.push(order(b,b.player,o.item,'ask',o.agreed ,'Provisional negotiated retail price.',o.customer));}
 // Wholesale is simultaneous among merchants. Customers buy retail only.
 for(const o of orders.filter(o=>o.side==='bid'))o.counterparty='shop';
 for(const i of s.manifest.config.items)if(s.markets[i.id].stock)orders.push(order(b,'shop',i.id,'ask',primaryAsk(s,i),'Limited public wholesale stock.'));
 for(const a of s.agents.filter(isFighter)){const id=need(b,a);if(!id)continue;const abandoned=b.offers.some(o=>o.customer===a.id&&o.status==='abandoned');const candidates=orders.filter(o=>(!abandoned||o.owner!==b.player)&&o.side==='ask'&&o.item===id&&o.owner!=='shop'&&(!o.counterparty||o.counterparty===a.id)).filter(o=>o.price<=customerLimit(b,a,o.owner,id));const chosen=candidates.sort((x,y)=>{const rx=relationship(b,a.id,x.owner),ry=relationship(b,a.id,y.owner);return x.price*(1-rx.preference*.005)-y.price*(1-ry.preference*.005)||x.priority-y.priority;})[0];if(chosen)orders.push(order(b,a.id,id,'bid',chosen.price,`I chose ${merchant(b,chosen.owner).name}'s affordable useful offer; price and past deals matter.`,chosen.owner));else note(b,`${a.name} waited: no useful retail offer met their budget and limits.`);}
 const before=s.trades.length;settleRound(s,orders);const trades=s.trades.slice(before);
 for(const t of trades.filter(t=>isFighter(s.agents.find(a=>a.id===t.buyer) ))){const r=relationship(b,t.buyer,t.seller);r.purchases++;r.paid+=t.price;r.preference=Math.min(5,r.preference+1);note(b,`${merchant(b,t.buyer).name} bought ${s.manifest.config.items.find(i=>i.id===t.item) .name} from ${merchant(b,t.seller).name} for ${t.price} g; repeat-deal preference +1 (bounded).`);for(const ad of b.promotions.filter(ad=>ad.merchant===t.seller&&ad.item===t.item&&ad.end>=s.round&&ad.customers.includes(t.buyer))){ad.sales++;if(ad.kind==='value'&&t.price>s.manifest.config.items.find(i=>i.id===t.item) .reference){r.trust=Math.max(-5,r.trust-2);note(b,`${merchant(b,t.buyer).name} lost promotion trust in ${merchant(b,t.seller).name}: the fair-price promise was broken. An expensive purchase alone is not a scam.`);}else r.trust=Math.min(5,r.trust+1);}}
 for(const o of b.offers.filter(o=>o.status==='accepted')){const t=trades.find(t=>t.buyer===o.customer);if(t?.seller!==b.player){const r=relationship(b,o.customer,b.player);r.abandoned++;note(b,`${merchant(b,o.customer).name} ${t?`bought from ${merchant(b,t.seller).name} because a better acceptable alternative won`:'did not complete the deal; the reserved copy found no matching buyer'}. Reservation released.`);}}
 for(const ad of b.promotions.filter(ad=>ad.end===s.round&&ad.sales===0))note(b,`${merchant(b,ad.merchant).name}'s campaign expired without a sale. The advertising bill remains paid.`);
 for(const o of b.offers.filter(o=>o.status==='open'&&o.attempts>0)){relationship(b,o.customer,b.player).abandoned++;note(b,`${merchant(b,o.customer).name}'s unanswered negotiation expired. No cash or copies transferred.`);}b.bids={};b.listings={};b.offers=[];s.orders=[];b.phase=s.round===10?'complete':'settlement';note(b,`Day ${s.round} closed: ${trades.length} trades. All unfilled orders and negotiation reservations expired.`);assertBazaar(b);return b;
}
export function nextDay(b       ){if(b.phase!=='settlement')throw Error('Settle the current day first.');openDay(b);return b;}
export function assertBazaar(b       ){assertAccounting(b.state);if(b.advertisingTreasury!==Object.values(b.advertising).reduce((n,v)=>n+v,0))throw Error('Advertising accounting mismatch.');if(reservations(b).available<0)throw Error('Invalid cash reservation.');}
export function results(b       ){return b.state.agents.filter(a=>!isFighter(a)).map(a=>({id:a.id,name:a.name,starting:b.startCash,cash:a.cash,realized:a.profit,advertising:b.advertising[a.id]??0,netRealized:a.profit-(b.advertising[a.id]??0),inventory:Object.entries(a.inventory).filter(([,lots])=>lots.length).map(([item,lots])=>({item,copies:lots.length,costBasis:lots.reduce((n,l)=>n+l.cost,0)})),won:a.cash>b.startCash}));}
export function bazaarDigest(b       ){return JSON.stringify({economy:digest(b.state),phase:b.phase,actions:b.actions,relationships:b.relationships,advertising:b.advertising,promotions:b.promotions,results:results(b)});}
export function exportBazaar(b       ){return JSON.stringify({format:'bazaar-v1',seed:b.state.manifest.seed,mode:b.mode,rules:b.state.manifest,day:b.state.round,phase:b.phase,actions:b.actions,events:b.state.events,results:results(b),digest:bazaarDigest(b)},null,2);}
const canonical=(value        )=>JSON.stringify(value,(_key,v)=>typeof v==='number'&&!Number.isInteger(v)?Math.round(v*1e6)/1e6:v);
export function importBazaar(text       ){if(text.length>8000000)throw Error('Bazaar export too large.');const x=JSON.parse(text);if(x.format!=='bazaar-v1'||!Number.isSafeInteger(x.seed)||x.seed<0||x.seed>4294967295||!['shop','spectate'].includes(x.mode)||!Number.isInteger(x.day)||x.day<1||x.day>10||!['decisions','settlement','complete'].includes(x.phase)||!Array.isArray(x.actions)||x.actions.length>1000)throw Error('Invalid bazaar replay.');const b=startBazaar(x.seed,x.mode);if(JSON.stringify({...x.rules,interventions:[]})!==JSON.stringify(b.state.manifest))throw Error('Unsupported scenario rules.');let n=0;for(let day=1;day<=x.day;day++){while(n<x.actions.length&&x.actions[n].day===day){const a=x.actions[n++];if(a.phase!=='decisions')throw Error('Invalid action phase.');act(b,a);}if(day<x.day||x.phase!=='decisions')settleDay(b);if(day<x.day)nextDay(b);}if(canonical(x.events)!==canonical(b.state.events)||canonical(x.results)!==canonical(results(b))||JSON.stringify(x.rules)!==JSON.stringify(b.state.manifest)||n!==x.actions.length||b.phase!==x.phase||bazaarDigest(b)!==x.digest)throw Error('Replay checksum mismatch.');return b;}
