                                                            
const base              = {
 id:'practical',label:'Practical shopper',blurb:'A role-based shopper with a budget. This fallback is a simulation choice, not a researched lore portrait.',symbol:'✦',color:'#4b948b',mode:'buyer',
 patience:10,reserveBps:500,maxPayBps:17500,impulseBps:0,prestigeBps:0,loyaltyBps:1800,memoryBps:350,
 buy:'Useful gear. Acceptable price. That will do.',wait:'The wallet has veto power.',sell:'A fair offer, if someone wants it.',loss:'There goes the contingency fund.',
};
const champion=(id       ,label       ,blurb       ,traits                     )            =>({...base,id:id.toLowerCase(),label,blurb,source:`https://www.leagueoflegends.com/en-us/champions/${id.toLowerCase()}/`,...traits});
export const championPersonalities                             = {
 Jinx:champion('Jinx','Chaos shopper','Lore cue: impulsive, inventive and chaotic. Our interpretation: changes priorities every three rounds and stretches her budget.',{symbol:'✹',color:'#c34e92',patience:2,reserveBps:0,maxPayBps:23500,impulseBps:7000,loyaltyBps:0,memoryBps:80,buy:'Ooh. New toy. The budget can catch up!',wait:'Who put a price tag on the fun?',loss:'That was expensive. Anyway…'}),
 Ahri:champion('Ahri','Reflective wanderer','Lore cue: seeks memories and understanding. Our interpretation: keeps a reserve and learns strongly from expensive purchases.',{color:'#c276ad',reserveBps:1400,memoryBps:1100,patience:12,buy:'A useful find. I will remember what it cost.',wait:'A little patience leaves room for a better choice.'}),
 Yasuo:champion('Yasuo','Stubborn wanderer','Lore cue: deep resolve and a wandering swordsman. Our interpretation: strong attachment to his build, little interest in fashionable substitutes.',{color:'#709fac',loyaltyBps:6500,patience:18,maxPayBps:19000,buy:'The plan holds. So does the blade.',wait:'The right blade is worth waiting for.'}),
 Lux:champion('Lux','Bright-side buyer','Lore cue: optimism and resilience. Our interpretation: flexible shopping and a modest cushion for the next purchase.',{color:'#bb962c',impulseBps:1400,reserveBps:700,maxPayBps:18500,buy:'An upgrade! Let us call that progress.',wait:'There is a bright side. It is just not in stock.'}),
 Garen:champion('Garen','Disciplined quartermaster','Lore cue: duty, armor and Demacian ideals. Our interpretation: follows his build closely and protects a cash reserve.',{symbol:'⚑',color:'#5680b2',reserveBps:1800,loyaltyBps:7000,maxPayBps:16000,patience:16,buy:'Equipment secured. Expenditure justified.',wait:'Discipline includes not buying everything.'}),
 Teemo:champion('Teemo','Prepared scout','Lore cue: enthusiastic scouting and a strict code. Our interpretation: patient, budget-conscious, loyal to prepared equipment.',{symbol:'♧',color:'#71924e',reserveBps:1200,loyaltyBps:4000,maxPayBps:15500,patience:8,buy:'Supplies acquired. Receipt acquired. All prepared!',wait:'A scout is prepared. A scout is also underfunded.'}),
 Thresh:champion('Thresh','Patient collector','Lore cue: cunning and slow, inventive torment. Our interpretation: waits for favored equipment and remembers costly purchases.',{symbol:'⌑',color:'#478d75',loyaltyBps:5500,patience:20,memoryBps:900,buy:'Another acquisition for the collection.',wait:'I have time. The seller has inventory.'}),
 Ashe:champion('Ashe','Careful leader','Lore cue: stoic, intelligent and idealistic leadership. Our interpretation: conservative price limits and substantial reserves.',{color:'#518fa9',reserveBps:2000,maxPayBps:15500,patience:14,memoryBps:800,buy:'A measured purchase. We still have provisions.',wait:'Tomorrow also needs a budget.'}),
 Darius:champion('Darius','Decisive bidder','Lore cue: unwavering conviction and decisive action. Our interpretation: commits to the build and pays more to finish a delayed purchase.',{symbol:'⚒',color:'#b95751',patience:3,maxPayBps:20500,loyaltyBps:5000,reserveBps:0,buy:'The price is settled. Next.',wait:'This shopping campaign is taking too long.'}),
 Veigar:champion('Veigar','Grandiose collector','Lore cue: stubborn sorcery and being underestimated. Our interpretation: favors expensive useful equipment and clings to his build.',{symbol:'☾',color:'#9166af',prestigeBps:6500,loyaltyBps:3500,maxPayBps:22000,reserveBps:0,buy:'BEHOLD MY ENTIRELY REASONABLE EXPENDITURE!',wait:'My purchasing power has been underestimated!'}),
 MissFortune:champion('MissFortune','Hard-nosed captain','Lore cue: ruthless and unpredictable captain. Our interpretation: disciplined price limits, adaptable item choice and strong price memory.',{symbol:'⚓',color:'#ae6955',reserveBps:1200,memoryBps:1200,loyaltyBps:500,maxPayBps:16500,buy:'Good gear. Nobody gets a free tip.',wait:'I can wait longer than that markup.'}),
 Leona:champion('Leona','Steadfast guardian','Lore cue: an armored defender of Mount Targon. Our interpretation: preserves a reserve and sticks to a prepared build.',{symbol:'☀',color:'#b48b39',reserveBps:1500,loyaltyBps:6000,patience:15,maxPayBps:17000,buy:'Another piece of the plan is in place.',wait:'The sun will rise. My budget will not.'}),
 Ornn:champion('Ornn','Unimpressed craftsman','Lore cue: solitary forging and craftsmanship. Our interpretation: strict price ceiling, high build loyalty and very long patience. No forging mechanic.',{symbol:'⚒',color:'#a36a43',patience:24,maxPayBps:15000,loyaltyBps:8000,reserveBps:1000,memoryBps:1000,buy:'Acceptable. Barely.',wait:'At that price? I will stand here and disapprove.'}),
 Draven:champion('Draven','Luxury showman','Lore cue: spectacle, acclaim and brash perfection. Our interpretation: favors costly useful equipment and pays a large prestige premium.',{symbol:'★',color:'#bf6454',prestigeBps:9000,maxPayBps:26000,patience:2,reserveBps:0,memoryBps:50,loyaltyBps:1000,buy:'You are welcome for the sales figure.',wait:'Why is the shop not impressed by my name?'}),
};
const trader=(id       ,label       ,blurb       ,mode                    ,traits                     )            =>({...base,id,label,blurb,mode,...traits});
export const traderPersonalities = [
 trader('bagholder','Barnaby Bags','The Bagholder · refuses asks below FIFO cost including the seller fee. His conviction can leave him stuck.','bagholder',{symbol:'▣',color:'#a379b2',maxPayBps:14000,patience:40,buy:'This is a long-term position. Starting right now.',wait:'It is only a loss if I sell. The fees disagree.',sell:'Patient capital seeks a patient customer.',loss:'My investment horizon just became longer.'}),
 trader('bargain','Nib the Bargain Goblin','Buys only near reference value. Discounts old stock quickly, even when that realizes a loss.','bargain',{symbol:'♧',color:'#71a56a',maxPayBps:11200,patience:5,buy:'Mine! At a price I can tolerate.',wait:'I refuse to pay full imaginary retail.',sell:'Fine. Discount. Do not tell the other goblins.',loss:'The receipt has betrayed me.'}),
 trader('dealer','Mabel Fairweather','The Patient Dealer · buys against public build demand, keeps a reserve and gradually reduces old asking prices.','dealer',{symbol:'◈',color:'#589c95',reserveBps:1600,maxPayBps:13000,patience:16,buy:'Someone has this on a shopping list. Let us see.',wait:'An empty till is not a strategy.',sell:'Good stock. A price that gets more reasonable with age.',loss:'Sometimes the lesson costs more than the stock.'}),
 trader('corner','Baron Bootstraps','The Corner King · concentrates on one useful market, then attempts an exit. No control of production or guaranteed buyers.','corner',{symbol:'♛',color:'#c5903e',maxPayBps:17000,patience:30,reserveBps:0,buy:'A modest acquisition for my modest empire.',wait:'My empire is experiencing a liquidity interval.',sell:'The empire is open for business. Please form a queue.',loss:'We are downsizing the empire.'}),
];
export const hypePersonality=trader('hype','Pip Moonshot','The Hype Merchant · chases executed price increases and offers a sharp discount when momentum turns negative.','hype',{symbol:'↗',color:'#ca6e6c',maxPayBps:16000,patience:3,reserveBps:0,buy:'The line went up. I have seen enough!',wait:'Waiting for the line to tell me what to think.',sell:'New strategy: be somewhere else.',loss:'The line and I are no longer on speaking terms.'});
export const practicalPersonality=base;
export function personalityOf(s      ,a      )                       {
 if(!s.manifest.config.story)return undefined;
 if(a.strategy.endsWith('fighter'))return s.manifest.config.archetypes[a.archetype].personality;
 const traders=s.agents.filter(a=>!a.strategy.endsWith('fighter'));
 return s.manifest.config.story.traders[traders.findIndex(t=>t.id===a.id)];
}
// Independent keyed variation: never consumes the auction's random priority stream.
export function characterRoll(seed       ,key       )        {
 let h=seed>>>0;for(let n=0;n<key.length;n++)h=Math.imul(h^key.charCodeAt(n),16777619);h=Math.imul(h^(h>>>16),0x85ebca6b);h=Math.imul(h^(h>>>13),0xc2b2ae35);return ((h^(h>>>16))>>>0)/4294967296;
}
