import { merchant, campaigns } from './bazaar.js';
                                                 
import { fee } from './engine.js';
import { campaignPreview, dealPreview, displayName, negotiationAvailability, modeState } from './shop-feedback.js';
export const esc=(x        )=>String(x??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
export const gold=(n       )=>n.toLocaleString('en-US'),signed=(n       )=>(n>=0?'+':'−')+gold(Math.abs(n));
export const image=(path                 )=>path?`<img src="./assets/${esc(path)}" alt=""/>`:'';
export function activeModeHtml(b       ,selected               ){const m=modeState(b.mode,selected);return `<span id="active-mode">Active run: <b>${m.active}</b></span><span id="pending-mode">${m.pending?`Selected for next run: ${m.selected}. Click New run to apply; this run continues unchanged.`:'The selected mode applies when you click New run.'}</span>`;}
export function dealHtml(b       ,o      ,draft        ){const p=dealPreview(b,o),availability=negotiationAvailability(b,o),i=b.state.manifest.config.items.find(i=>i.id===o.item) ;if(p.reserved)return `<div class="customer-offer agreed-deal"><strong>Provisionally agreed: ${gold(p.price)} g</strong><p>${image(i.icon)} Reserved: <b>${esc(i.name)} × 1</b></p><dl><dt>Expected seller proceeds</dt><dd>${gold(p.proceeds)} g after ${p.sellerFee} g seller fee</dd><dt>FIFO acquisition cost</dt><dd>${p.cost===null?'Unavailable':gold(p.cost)+' g'}</dd><dt>Expected trading profit / loss</dt><dd>${p.profit===null?'Unavailable':signed(p.profit)+' g'}</dd></dl><p>A cheaper acceptable rival may still win at settlement. These are estimates for a completed sale.</p><small>Opening offer: ${gold(o.price)} g · ${o.attempts} attempt(s) used.</small><button data-negotiate="reject" data-customer="${o.customer}">Release deal</button><small>Releases the copy; the customer records a declined negotiation.</small></div>`;
const draftPrice=Number(draft??String(o.price)),draftWhy=Number.isSafeInteger(draftPrice)&&draftPrice>=1&&draftPrice<=i.reference*4?'':'Enter a positive integer within the public 4× reference cap.';
return `<div class="customer-offer"><strong>Opening offer: ${gold(o.price)} g</strong><span>${o.status} · ${availability.remaining} proposal(s) remaining</span><label>Counteroffer<input aria-label="Counteroffer for ${esc(displayName(b,o.customer))}" id="counter-${o.customer}" type="number" min="1" value="${esc(draft??String(o.price))}" ${availability.canPropose?'':'disabled'}/></label><div class="deal-actions"><button data-negotiate="accept" data-customer="${o.customer}" ${availability.canPropose?'':'disabled'}>Accept opening offer</button><button data-negotiate="counter" data-customer="${o.customer}" ${availability.canPropose&&!draftWhy?'':'disabled'}>Counter</button><button data-negotiate="reject" data-customer="${o.customer}" ${availability.canReject?'':'disabled'}>Reject offer</button></div><small class="action-reason" id="counter-reason-${o.customer}">${esc(availability.why||draftWhy)}</small></div>`;}
export function adHtml(b       ,id       ){return Object.entries(campaigns).map(([kind,c])=>{const p=campaignPreview(b,id,kind                          );return `<article class="campaign-choice"><b>${c.label}</b><p>${c.cost} g · ${c.duration} days · up to ${c.reach} exposures.<br/>${p.eligible} currently eligible customers; maximum planned exposure ${p.maximumExposure}.</p><p>Personality-sensitive attention and price effect, capped at 10%. Utility, affordability and price ceilings still apply. Eligible reach does not guarantee exposure or sales.</p>${kind==='value'?'<small>Promises a price at or below reference; a broken promise can reduce promotion trust.</small>':''}<button data-ad="${kind}" ${p.reason?'disabled':''}>Purchase ${c.label} · ${c.cost} g</button>${p.reason?`<small class="action-reason">${esc(p.reason)}</small>`:''}</article>`;}).join('');}
export function bidDraft(b       ,id       ,value       ){const price=Number(value),a=merchant(b),old=b.bids[id]??0,others=Object.entries(b.bids).filter(([item])=>item!==id).reduce((n,[,p])=>n+p+fee(p,b.state.buyerFeeBps),0),i=b.state.manifest.config.items.find(i=>i.id===id) ,cost=Number.isFinite(price)&&price>0?price+fee(price,b.state.buyerFeeBps):0;let why='';if(!Number.isSafeInteger(price)||price<1||price>i.reference*4)why='Enter a positive integer within the public 4× reference cap.';else if(others+cost>a.cash)why='This draft exceeds unreserved cash, including acquisition fees. Sale proceeds cannot fund it.';else if(a.inventory[id].length>=2)why='Per-item inventory capacity is full.';else if(Object.values(a.inventory).reduce((n,l)=>n+l.length,0)+Object.keys(b.bids).filter(item=>item!==id).length+1>8)why='Combined inventory and saved bids exceed capacity.';return {price,cost,why,changed:old!==price,saved:old};}
