import { act, campaigns, exportBazaar, importBazaar, merchant, need, nextDay, relationship, reservations, results, settleDay, startBazaar } from './bazaar.js';
                                                        
import { fee, holdings, isFighter, primaryAsk } from './engine.js';
import { editionAt, receipts } from './newspaper.js';
import { download, tradesCsv, metricsCsv } from './exports.js';
import { activeModeHtml, adHtml, bidDraft, dealHtml, esc, gold as g, image as icon, signed } from './shop-view.js';
import { daySummary, displayName, displayText, inventoryFeedback, memoryDescription, newspaperState, stallSummary } from './shop-feedback.js';

let b=startBazaar(),playing=false,follow='',pauseSales=false,prediction='',presentation=false;
let selectedMode               ='shop',selectedSeed='42',adItem='';
let drafts                      ={};
let message='Welcome. Save wholesale bids on day one; acquired stock becomes saleable at the next opening.';
const root=document.querySelector             ('#root') ;
const item=(id       )=>b.state.manifest.config.items.find(i=>i.id===id) ;
const name=(id       )=>displayName(b,id),text=(value       )=>displayText(b,value).replace('repeat-deal preference +1 (bounded).','the completed deal strengthened this customer’s preference for the stall.').replace('merchant preference decreased by 1 (bounded).','the customer is less keen on this stall.');
const input=(id       )=>document.getElementById(id)                    ;
const disabled=(value        )=>value?'disabled':'';
const stat=(label       ,value       ,help       )=>`<div class="stat"><span>${label}</span><strong>${value}</strong><small>${help}</small></div>`;
function render(){
 const s=b.state,a=merchant(b),r=reservations(b),open=b.phase==='decisions',shop=b.mode==='shop',complete=b.phase==='complete';
 const customers=s.agents.filter(isFighter),merchants=s.agents.filter(a=>!isFighter(a)),paperState=newspaperState(b),paper=editionAt(paperState,s.metrics.at(-1)?.round??0);
 const owned=s.manifest.config.items.filter(i=>a.inventory[i.id].length);if(!owned.some(i=>i.id===adItem))adItem=owned[0]?.id??'';
 root.innerHTML=`<div class="shop-shell"><header class="shop-header"><div><span class="eyebrow">LEAGUE ITEM EXCHANGE · STANDALONE FICTIONAL BAZAAR</span><h1>${shop?'Ten days. One little shop.':'Ten days. A whole bazaar.'}</h1><p>${shop?'Buy finite stock. Know your customers. Keep the receipts.':'Follow recurring customers and rival stalls. The economy progresses without human orders.'}</p></div><a href="./?legacy=1">Legacy experiments & full recording tools ↗</a></header>
 <section class="shop-toolbar"><div class="run-setup"><label>Mode for new run<select id="mode"><option value="shop" ${selectedMode==='shop'?'selected':''}>Run a shop</option><option value="spectate" ${selectedMode==='spectate'?'selected':''}>Spectate · autonomous</option></select></label><label>Seed for new run<input id="shop-seed" type="number" value="${esc(selectedSeed)}"/></label><button id="restart">New run</button></div><div class="run-controls"><strong>Day ${s.round} / 10 · ${complete?'COMPLETE':open?'OPENING & DECISIONS':'SETTLEMENT'}</strong><button id="advance" class="primary" ${disabled(complete)}>${open?'Settle day':complete?'Run complete':'Open next day'}</button>${shop?'':`<button id="auto" ${disabled(complete)}>${complete?'Playback complete':playing?'Pause':'Run automatically'}</button>`}<button id="present">${presentation?'Exit presentation':'Presentation'}</button></div><div class="run-files"><button id="export-shop">Export run</button><button id="import-shop">Import / verify replay</button><button id="csv">Trades CSV</button><button id="metrics">Metrics CSV</button></div></section>
 <div class="mode-status">${activeModeHtml(b,selectedMode)}${presentation?'<strong class="presentation-status">PRESENTATION ACTIVE · manual trading remains available</strong>':''}</div><p class="shop-notice" role="status">${esc(message)}</p><p class="muted">${s.manifest.interventions.length?'ASSISTED RUN · developer interventions recorded':'Unassisted run'} · ${s.buyerFeeBps/100}% buyer / ${s.sellerFeeBps/100}% seller fee · No future-event information.</p>
 <section class="stats">${shop?stat('Spendable cash',g(a.cash)+' g','Initial '+g(b.startCash)+' g')+stat('Reserved bids',g(r.cash)+' g',g(r.available)+' g still available')+stat('Realized trading profit',signed(a.profit)+' g','FIFO acquisition costs and trading fees')+stat('Advertising',g(b.advertising[b.player]??0)+' g','Net realized '+signed(a.profit-(b.advertising[b.player]??0))+' g')+stat('Owned copies',String(holdings(a)),'Unsold stock is not spendable cash'):stat('Merchants’ cash',g(merchants.reduce((n,a)=>n+a.cash,0))+' g','Four stalls · equal 12,000 g starts')+stat('Completed customer purchases',String(s.trades.filter(t=>isFighter(merchant(b,t.buyer))).length),'Finite demand · maximum 24 purchases')+stat('Merchant realized profit',signed(merchants.reduce((n,a)=>n+a.profit,0))+' g','Unsold inventory excluded')+stat('Paid advertising',g(Object.values(b.advertising).reduce((n,v)=>n+v,0))+' g','Real cash, not newspaper influence')+stat('Customers still shopping',String(customers.filter(a=>need(b,a)).length),'Completed builds create no further demand')}</section>
 ${b.phase!=='decisions'?settlementHtml():''}${complete?endScreen():''}
 <section class="shop-focus"><div><h2>${shop?'Your counter':'Follow the economy'}</h2><p>${open?'Opening wholesale quotes precede the simultaneous auction. Stock permits at most one wholesale copy per item today; the executed midpoint price may differ. Sale proceeds cannot fund today’s bids.':'The day has settled. All unfilled bids, listings and provisional deals expired; unused reservations were released.'}</p></div><div class="follow-controls"><label>Follow<select id="follow"><option value="">All characters</option>${s.agents.map(a=>`<option value="${a.id}" ${follow===a.id?'selected':''}>${esc(name(a.id))}</option>`).join('')}</select></label><label class="check-label"><input id="pause-sale" type="checkbox" ${pauseSales?'checked':''}/> Pause on customer sale</label><button id="predict" ${disabled(s.metrics.length>0)}>Prediction</button><button id="developer" ${disabled(!open||s.round===10)}>Developer interventions</button></div></section>
 <section><h2>Recurring customers <small>Finite three-item builds</small></h2><div class="shop-customers">${customers.map(c=>{const id=need(b,c),o=b.offers.find(o=>o.customer===c.id),profile=s.manifest.config.archetypes[c.archetype],rel=relationship(b,c.id,shop?b.player:follow&&merchants.some(a=>a.id===follow)?follow:b.player);return `<article class="customer-card ${follow===c.id?'followed':''}"><div class="customer-top">${icon(profile.icon)}<div><h3>${esc(name(c.id))}</h3><span>${esc(profile.personality .label)}</span></div><button data-inspect="${c.id}">Inspect</button></div><p>${id?`${icon(item(id).icon)} Seeking <b>${esc(item(id).name)}</b>`:'✓ Build complete · no further demand'}</p><small>${c.equipped.length}/3 equipped · ${g(c.cash)} g budget</small><p class="customer-memory">${shop?esc(memoryDescription(rel)):customerMemoryHtml(c.id)}</p>${o&&shop&&open?dealHtml(b,o,drafts['counter-'+c.id]):''}</article>`;}).join('')}</div></section>
 <section id="stalls"><h2>${shop?'Rival stalls':'The merchant stalls'}</h2><div class="stall-grid">${merchants.filter(a=>!shop||a.id!==b.player).map(a=>{const stall=stallSummary(b,a.id);return `<article class="stall-card ${follow===a.id?'followed':''}"><h3>${esc(stall.name)}</h3><p>${esc(stall.strategy)}</p><b>${g(stall.cash)} g cash · ${stall.copies} held copies</b><p>${stall.listings.map(o=>`${icon(item(o.item).icon)} ${esc(item(o.item).name)}: ${g(o.price)} g`).join('<br/>')||(open?'No public retail listings.':'Day closed; listings expired.')}</p><small>${esc(stall.latest)}</small><button data-inspect="${a.id}">Inspect stall</button></article>`;}).join('')}</div></section>
 <section><h2>${shop?'Your inventory & limited wholesale':'Public item markets'}</h2>${shop?`<div class="shop-batch"><button id="default-list" ${disabled(!open||!owned.some(i=>!r.copies.has(i.id)))}>Save asks at cost + 15%</button><button id="withdraw" ${disabled(!open||!Object.keys(b.bids).length&&!Object.keys(b.listings).length)}>Withdraw saved bids & unreserved listings</button><span>One listed copy per item per day. Drafts do nothing until saved. Acquisitions become saleable tomorrow.</span></div>`:''}<div class="shop-items">${s.manifest.config.items.map(i=>inventoryHtml(i.id)).join('')}</div></section>
 <section class="shop-columns"><div><h2>Paid advertising</h2><p>Separate from factual reporting. Exposure and later purchases are observed together; that does not prove the campaign caused a sale.</p>${shop&&open?`<label>Owned inventory to promote<select id="ad-item">${owned.map(i=>`<option value="${i.id}" ${adItem===i.id?'selected':''}>${esc(i.name)}</option>`).join('')}</select></label><div id="campaign-choices">${adHtml(b,adItem)}</div>`:''}<div class="campaign-history">${b.promotions.map(p=>`<article><b>PAID AD · ${esc(name(p.merchant))}</b><p>${campaigns[p.kind].label} for ${esc(item(p.item).name)} · days ${p.start}–${p.end}</p><p>${p.customers.length} actual exposures: ${p.customers.map(id=>esc(name(id))).join(', ')||'none'}<br/>${p.sales} completed purchases following exposure · ${p.end<s.round?'expired':'active through its final settlement'}</p><small>Purchases following exposure are not evidence of causal uplift.</small></article>`).join('')||'<p>No campaign purchased yet.</p>'}</div></div><div class="newspaper shop-paper"><span class="eyebrow">FACTUAL REPORTING · THROUGH LAST SETTLED DAY</span><h2>The Runeterra Ledger</h2>${paper.articles.map(p=>`<article><h3>${esc(text(p.title))}</h3><p>${esc(text(p.body))}</p><small>${esc(text(p.evidence))}</small>${p.quote?`<p class="fictional-quote">“${esc(text(p.quote))}” — ${esc(text(p.speaker??''))} · fictional commentary</p>`:''}</article>`).join('')}<button id="archive">Edition archive</button></div></section>
 <section class="shop-columns"><div><h2>Consequences & decisions</h2>${consequencesHtml()}</div><div><h2>Recorded trade receipts</h2>${s.trades.filter(t=>!follow||t.buyer===follow||t.seller===follow).slice(-20).reverse().map(t=>`<button class="shop-receipt" data-trade="${t.id}">Day ${t.round} · ${esc(name(t.buyer))} ← ${esc(name(t.seller))}<br/>${esc(item(t.item).name)} · ${g(t.price)} g · fees ${t.buyerFee+t.sellerFee} g</button>`).join('')||'<p>No matching completed trades yet.</p>'}</div></section><footer>Accounting checked after every action and settlement. Advertising treasury: ${g(b.advertisingTreasury)} g (included in shop treasury). No guaranteed customers or liquidation.</footer></div><dialog id="shop-dialog"><button id="close-shop-dialog">Close</button><div id="shop-dialog-content"></div></dialog>`;
 document.body.classList.toggle('shop-presentation',presentation);
}
function customerMemoryHtml(id       ){const rows=b.state.agents.filter(a=>!isFighter(a)).map(a=>({a,r:relationship(b,id,a.id)})).filter(x=>x.r.purchases||x.r.preference||x.r.trust);return rows.map(x=>`<span><b>${esc(name(x.a.id))}:</b> ${esc(memoryDescription(x.r,false))}</span>`).join('<br/>')||'No completed merchant relationships yet.';}
function inventoryHtml(id       ){const i=item(id),open=b.phase==='decisions',shop=b.mode==='shop',f=inventoryFeedback(b,id),quote=open?(b.state.markets[id].stock?primaryAsk(b.state,i):null):(b.state.events.filter(e=>e.round===b.state.round&&e.type==='order-submitted').map(e=>e.data.order                                                       ).find(o=>o.owner==='shop'&&o.item===id&&o.side==='ask')?.price??null),bidValue=drafts['bid-'+id]??String(b.bids[id]??Math.floor((quote??i.reference)*1.05)),draft=bidDraft(b,id,bidValue),askValue=drafts['ask-'+id]??String(b.listings[id]??(f.cost?Math.ceil(f.cost*1.15):i.reference)),askInvalid=!Number.isSafeInteger(Number(askValue))||Number(askValue)<1||Number(askValue)>i.reference*4;
return `<article class="shop-item" data-inventory="${id}">${icon(i.icon)}<h3>${esc(i.name)}</h3><button data-market="${id}">Inspect market</button><p><b>${open?'Opening wholesale quote':'Wholesale minimum in settled batch'}: ${quote===null?'No eligible wholesale supply':g(quote)+' g'}</b><br/>${open?'Opening stock':'Stock remaining after settlement'}: ${b.state.markets[id].stock} · at most one wholesale fill per item/day</p><p>Seeking now: ${f.customers.map(id=>esc(name(id))).join(', ')||'No current customers'}</p>${shop?`<dl><dt>Owned / listed / reserved / available</dt><dd>${f.owned} / ${f.listed} / ${f.reserved} / ${f.available}</dd><dt>FIFO cost of saleable copy</dt><dd>${f.cost===null?'—':g(f.cost)+' g including acquisition fee'}</dd><dt>Break-even ask after seller fee</dt><dd>${f.cost===null?'—':f.breakEven===null?'No finite break-even':g(f.breakEven)+' g'}</dd></dl>`:''}<p>Best visible ${shop?'rival':'other stall'} ask: ${f.rival?`${esc(name(f.rival.owner))} · ${g(f.rival.price)} g`:open?'None':'Expired; open tomorrow for new listings'}</p>${shop&&open?`<div class="order-editor"><label>Wholesale bid draft<input id="bid-${id}" type="number" min="1" value="${esc(bidValue)}"/></label><small id="bid-reservation-${id}">Estimated maximum cash reservation: ${g(draft.cost)} g including ${fee(Math.max(0,draft.price||0),b.state.buyerFeeBps)} g fee.</small><p class="saved-order" id="bid-state-${id}">${b.bids[id]?`Saved bid: ${g(b.bids[id])} g${draft.changed?' · draft differs; save to replace':''}`:'Draft only · no wholesale bid saved'}</p><button data-bid="${id}" ${disabled(!!draft.why)}> ${b.bids[id]?'Replace saved bid':'Save bid'}</button><button data-withdraw-bid="${id}" ${disabled(!b.bids[id])}>Withdraw bid</button><small class="action-reason" id="bid-reason-${id}">${esc(draft.why)}</small>${f.owned?`<label>Retail ask draft<input id="ask-${id}" type="number" min="1" value="${esc(askValue)}" ${disabled(!!f.reserved)}/></label><p class="saved-order" id="ask-state-${id}">${b.listings[id]?`Saved listing: 1 copy at ${g(b.listings[id])} g`:'Draft only · no retail listing saved'}</p><button data-list="${id}" ${disabled(!!f.reserved||askInvalid)}>${b.listings[id]?'Replace saved listing':'Save listing'}</button><button data-withdraw-list="${id}" ${disabled(!b.listings[id]||!!f.reserved)}>Withdraw listing</button><small class="action-reason" id="ask-reason-${id}">${askInvalid?'Enter a positive integer within the public 4× reference cap.':''}</small>${f.reserved?'<small>Negotiated copy reserved. Release the customer deal before saving an item listing.</small>':''}`:''}</div>`:''}</article>`;}
function consequencesHtml(){const routine=b.report.filter(t=>t.includes(' waited:')),important=b.report.filter(t=>!t.includes(' waited:'));return important.map(t=>`<p>${esc(text(t))}</p>`).join('')+(routine.length?`<details><summary>${routine.length} routine customer waits</summary>${routine.map(t=>`<p>${esc(text(t))}</p>`).join('')}</details>`:'');}
function settlementHtml(){const d=daySummary(b),shop=b.mode==='shop';return `<section id="settlement-summary" class="settlement-summary" tabindex="-1"><span class="eyebrow">DAY ${d.day} RECEIPTS · ${shop?'YOUR STALL':'THE WHOLE ECONOMY'}</span><h2>Settlement results</h2><div class="summary-stats">${stat('Trading profit / loss',signed(d.tradingProfit)+' g','After FIFO costs and trading fees')+stat('Advertising purchased today','−'+g(d.advertising)+' g','Expenses paid during today’s opening/decisions')+stat('Net realized result today',signed(d.net)+' g','Trading profit less advertising')}</div><p>Cash from sales: +${g(d.saleProceeds)} g. Inventory acquisitions: −${g(d.acquisitionSpend)} g including fees. Acquisition spending is not a realized trading loss.</p>${d.sales.length?d.sales.map(r=>`<p class="meaningful-result"><button data-trade="${r.trade.id}">${esc(name(r.trade.buyer))} bought ${shop?'your':esc(name(r.trade.seller))+'’s'} ${esc(item(r.trade.item).name)} for ${g(r.trade.price)} g.</button> Trading profit: ${signed(r.profit )} g.</p>`).join(''):'<p>No completed retail sales for this summary.</p>'}${d.acquisitions.map(r=>`<p><button data-trade="${r.trade.id}">${esc(name(r.trade.buyer))} acquired ${esc(item(r.trade.item).name)} for ${g(r.trade.price)} g + ${r.trade.buyerFee} g acquisition fee.</button></p>`).join('')}<h3>Wholesale bid outcomes</h3>${d.bids.map(o=>`<p class="bid-outcome"><b>${shop?'':esc(name(o.owner))+' · '}${esc(item(o.item).name)} · ${o.status}</b><br/>${esc(o.text)} ${shop?'Saved limit: ':''}${shop?g(o.limit)+' g.':''}</p>`).join('')||'<p>No wholesale bids submitted.</p>'}${d.failures.length?`<h3>Negotiations & campaigns that did not complete</h3>${d.failures.map(t=>`<p>${esc(text(t))}</p>`).join('')}`:''}${d.relationships.length?`<h3>Customer relationships</h3>${d.relationships.map(t=>`<p>${esc(text(t))}</p>`).join('')}`:''}${d.rivalWins.length?`<details ${shop?'open':''}><summary>${d.rivalWins.length} ${shop?'rival':'merchant'} retail wins</summary>${d.rivalWins.map(r=>`<p>${esc(name(r.trade.buyer))} bought ${esc(item(r.trade.item).name)} from ${esc(name(r.trade.seller))} for ${g(r.trade.price)} g.</p>`).join('')}</details>`:''}${d.waits.length?`<details><summary>${d.waits.length} routine customer waits</summary>${d.waits.map(t=>`<p>${esc(t)}</p>`).join('')}</details>`:''}<p>All unfilled orders and provisional deals expired. Opening wholesale quotes are minimum asks, not guaranteed acquisition prices.</p></section>`;}
function endScreen(){const shop=b.mode==='shop',all=results(b),r=all.find(r=>r.id===b.player) ,pnl=receipts(b.state).rows.filter(r=>r.trade.seller===b.player&&r.profit!==null).sort((x,y)=>y.profit -x.profit );return `<section class="shop-ending"><span class="eyebrow">DAY TEN · FINAL RESULTS</span><h2>${shop?(r.won?'More cash in the till!':'The shop challenge is over.'):'The bazaar shutters are down.'}</h2>${shop?`<p>Starting cash ${g(r.starting)} g → ending cash ${g(r.cash)} g. ${r.won?'Cash challenge achieved.':'Ending spendable cash did not exceed the starting balance.'} Realized trading profit ${signed(r.realized)} g; advertising ${r.advertising} g; net realized ${signed(r.netRealized)} g.</p><p>Unsold inventory at original cost basis: ${r.inventory.map(l=>`${esc(item(l.item).name)} ×${l.copies}: ${g(l.costBasis)} g`).join(' · ')||'None'}. No liquidation value is assumed.</p>${pnl.length?`<button data-trade="${pnl[0].trade.id}">Best completed sale: ${signed(pnl[0].profit )} g</button><button data-trade="${pnl.at(-1) .trade.id}">Worst completed sale: ${signed(pnl.at(-1) .profit )} g</button>`:'<p>No completed resale deals.</p>'}`:''}<div class="final-results">${all.map(r=>`<article><h3>${esc(name(r.id))}</h3><p>${g(r.starting)} g start → ${g(r.cash)} g cash<br/>${signed(r.realized)} g realized − ${r.advertising} g advertising = ${signed(r.netRealized)} g net realized</p><p>Unsold cost basis: ${r.inventory.map(l=>`${esc(item(l.item).name)} ×${l.copies}: ${g(l.costBasis)} g`).join(' · ')||'None'}</p></article>`).join('')}</div>${prediction?`<p>Prediction: ${esc(name(prediction))}. ${all.filter(r=>r.realized===Math.max(...all.map(r=>r.realized))).map(r=>esc(name(r.id))).join(', ')} led realized trading profit.</p>`:''}<p>Progression is finished. Export or verify this replay, or choose a mode and start a New run.</p><button id="final-replay">Verify replay</button><button id="final-new">New run</button><details><summary>${shop?'Your consequential decision timeline':'Recorded merchant consequences'}</summary>${b.actions.map(a=>`<p>Day ${a.day} · ${a.kind} ${esc(a.item?item(a.item).name:a.customer?name(a.customer):'')} ${a.price??''}</p>`).join('')}${b.history.filter(h=>!h.text.includes(' waited:')&&(b.mode==='spectate'||/your|Your shop/.test(h.text))).map(h=>`<p>Day ${h.day}: ${esc(text(h.text))}</p>`).join('')}</details></section>`;}
function modal(html       ){playing=false;document.querySelector('#shop-dialog-content') .innerHTML=html;(document.querySelector('#shop-dialog')                     ).showModal();}
function revealSummary(){const summary=document.getElementById('settlement-summary');summary?.scrollIntoView({block:'start',behavior:'instant'});summary?.focus({preventScroll:true});}
function advance(){if(b.phase==='complete'){playing=false;return;}const settling=b.phase==='decisions';if(settling){const n=b.state.trades.length;settleDay(b);if(pauseSales&&b.state.trades.slice(n).some(t=>isFighter(merchant(b,t.buyer))))playing=false;message='Settlement complete. Review the day’s results; all unused reservations were released.';}else{nextDay(b);message=b.mode==='shop'?'New opening: review current needs, wholesale quotes, rival listings and saved orders.':'New opening: customers and merchants are making their autonomous decisions.';}drafts={};if(b.phase==='complete'){playing=false;message='Day ten complete. Review final results, export or verify the replay, or start a New run.';}render();if(settling&&!playing)revealSummary();}
function newRun(){playing=false;b=startBazaar(Number(selectedSeed)>>>0,selectedMode);selectedSeed=String(b.state.manifest.seed);drafts={};adItem='';prediction='';follow='';message=b.mode==='shop'?'New shop run. Save bids to acquire stock; every merchant starts with 12,000 g.':'New spectator run. All merchants act autonomously; Run automatically or Step to follow the economy.';render();document.querySelector('.shop-header')?.scrollIntoView({block:'start'});}
function importModal(){modal('<h2>Import & recompute replay</h2><textarea id="shop-import" aria-label="Bazaar replay JSON" rows="12"></textarea><button id="verify-shop">Verify pasted replay</button><button id="verify-current">Recompute current run</button>');}
root.addEventListener('change',e=>{const t=e.target                    ;if(t.id==='mode'){selectedMode=t.value                  ;document.querySelector('.mode-status') .innerHTML=activeModeHtml(b,selectedMode)+(presentation?'<strong>PRESENTATION ACTIVE</strong>':'');}else if(t.id==='shop-seed')selectedSeed=t.value;else if(t.id==='follow'){follow=t.value;render();}else if(t.id==='pause-sale')pauseSales=t.checked;else if(t.id==='ad-item'){adItem=t.value;document.querySelector('#campaign-choices') .innerHTML=adHtml(b,adItem);}});
root.addEventListener('input',e=>{const t=e.target                    ;if(t.id==='shop-seed'){selectedSeed=t.value;return;}if(!/^(bid|ask|counter)-/.test(t.id))return;drafts[t.id]=t.value;const id=t.id.replace(/^(bid|ask|counter)-/,'');if(t.id.startsWith('bid-')){const d=bidDraft(b,id,t.value);document.querySelector('#bid-reservation-'+id) .textContent=`Estimated maximum cash reservation: ${g(d.cost)} g including ${fee(Math.max(0,d.price||0),b.state.buyerFeeBps)} g fee.`;document.querySelector('#bid-reason-'+id) .textContent=d.why;document.querySelector('#bid-state-'+id) .textContent=d.saved?`Saved bid: ${g(d.saved)} g${d.changed?' · draft differs; save to replace':''}`:'Draft only · no wholesale bid saved';(document.querySelector(`[data-bid="${id}"]`)                     ).disabled=!!d.why;}else if(t.id.startsWith('ask-')){const price=Number(t.value),button=document.querySelector(`[data-list="${id}"]`)                     ;const invalid=!Number.isSafeInteger(price)||price<1||price>item(id).reference*4;button.disabled=reservations(b).copies.has(id)||invalid;document.querySelector('#ask-reason-'+id) .textContent=invalid?'Enter a positive integer within the public 4× reference cap.':'';document.querySelector('#ask-state-'+id) .textContent=b.listings[id]?`Saved listing: 1 copy at ${g(b.listings[id])} g · changed draft is not saved`:'Draft only · no retail listing saved';}else{const price=Number(t.value),o=b.offers.find(o=>o.customer===id) ;const invalid=!Number.isSafeInteger(price)||price<1||price>item(o.item).reference*4;(document.querySelector(`[data-negotiate="counter"][data-customer="${id}"]`)                     ).disabled=invalid;document.querySelector('#counter-reason-'+id) .textContent=invalid?'Enter a positive integer within the public 4× reference cap.':'';}});
root.addEventListener('click',e=>{const t=(e.target               ).closest('button')                     ;if(!t||t.disabled)return;try{
 if(t.id==='restart'||t.id==='final-new'){newRun();return;}
 if(t.id==='advance'){advance();return;}
 if(t.id==='auto'){if(b.phase==='complete')return;playing=!playing;message=playing?'Autonomous playback running.':'Playback paused.';render();return;}
 if(t.id==='present'){presentation=!presentation;message=presentation?'Presentation active. Manual order and negotiation controls remain usable.':'Presentation ended.';render();return;}
 if(t.dataset.bid){act(b,{kind:'bid',item:t.dataset.bid,price:Number(input('bid-'+t.dataset.bid).value)});message=`Saved wholesale bid for ${item(t.dataset.bid).name}; maximum cash is now reserved.`;}
 else if(t.dataset.list){act(b,{kind:'list',item:t.dataset.list,price:Number(input('ask-'+t.dataset.list).value)});message=`Saved one-copy retail listing for ${item(t.dataset.list).name}.`;}
 else if(t.dataset.withdrawBid){act(b,{kind:'bid',item:t.dataset.withdrawBid,price:0});message='Wholesale bid withdrawn; cash reservation released.';}
 else if(t.dataset.withdrawList){act(b,{kind:'list',item:t.dataset.withdrawList,price:0});message='Retail listing withdrawn; copy remains owned.';}
 else if(t.dataset.negotiate){act(b,{kind:t.dataset.negotiate                               ,customer:t.dataset.customer,price:t.dataset.negotiate==='reject'?undefined:Number(input('counter-'+t.dataset.customer).value)});message=b.report.at(-1) ;}
 else if(t.dataset.ad){act(b,{kind:'advertise',campaign:t.dataset.ad                ,item:adItem});message=b.report.at(-1) ;}
 else if(t.id==='default-list'){for(const i of b.state.manifest.config.items.filter(i=>merchant(b).inventory[i.id].length&&!reservations(b).copies.has(i.id)))act(b,{kind:'list',item:i.id,price:Math.min(i.reference*4,Math.ceil(merchant(b).inventory[i.id][0].cost*1.15))});message='Owned, unreserved inventory listed. Saved asks are shown on each item card.';}
 else if(t.id==='withdraw'){for(const id of Object.keys(b.bids))act(b,{kind:'bid',item:id,price:0});for(const id of Object.keys(b.listings))act(b,{kind:'list',item:id,price:0});message='Saved bids and unreserved listings withdrawn. Accepted deals must be released on customer cards.';}
 else if(t.id==='export-shop'){download('bazaar-run.json',exportBazaar(b),'application/json');message='Replay export requested; it includes rules, actions, events and results.';}
 else if(t.id==='csv'){download('bazaar-trades.csv',tradesCsv(b.state),'text/csv');return;}
 else if(t.id==='metrics'){download('bazaar-metrics.csv',metricsCsv(b.state),'text/csv');return;}
 else if(t.id==='import-shop'||t.id==='final-replay'){importModal();return;}
 else if(t.id==='verify-shop'||t.id==='verify-current'){b=importBazaar(t.id==='verify-current'?exportBazaar(b):input('shop-import').value);playing=false;drafts={};if(t.id==='verify-shop'){prediction='';selectedMode=b.mode;selectedSeed=String(b.state.manifest.seed);}message='Replay verified: recorded actions, events and results recomputed successfully.';}
 else if(t.id==='close-shop-dialog'){(document.querySelector('#shop-dialog')                     ).close();return;}
 else if(t.dataset.market){const i=item(t.dataset.market),m=b.state.markets[i.id];modal(`<h2>${esc(i.name)}</h2><p>Reference ${g(i.reference)} g · last executed ${g(m.last)} g ${m.lastRound===null?'(untraded)':`(day ${m.lastRound}; ${m.lastRound<b.state.round?'stale':'latest settlement'})`} · current stock ${m.stock} · manufactured ${m.manufactured}</p><table><thead><tr><th>Day</th><th>Executed average</th><th>Volume</th><th>Stock</th></tr></thead><tbody>${m.history.map(h=>`<tr><td>${h.round}</td><td>${h.price===null?'No trades':g(h.price)+' g'}</td><td>${h.volume}</td><td>${h.stock}</td></tr>`).join('')}</tbody></table><p>Opening minimum asks precede the batch. Midpoint fills and stock remaining after fills are separate observations. No sale or liquidation is implied by a stale price.</p>`);return;}
 else if(t.dataset.inspect){const a=merchant(b,t.dataset.inspect),traders=b.state.agents.filter(a=>!isFighter(a));modal(`<h2>${esc(name(a.id))}</h2><p>${g(a.cash)} g cash · ${signed(a.profit)} g realized</p><p>Gear: ${a.equipped.map(id=>esc(item(id).name)).join(', ')||'none'}</p><p>Inventory: ${Object.entries(a.inventory).filter(([,l])=>l.length).map(([id,l])=>`${esc(item(id).name)} ×${l.length}, FIFO cost basis ${g(l.reduce((n,l)=>n+l.cost,0))} g`).join('; ')||'none'}</p><p>${esc(b.state.manifest.config.story .traders[traders.findIndex(x=>x.id===a.id)]?.blurb??b.state.manifest.config.archetypes[a.archetype].personality .blurb)}</p>${isFighter(a)?traders.map(m=>{const r=relationship(b,a.id,m.id);return `<p><b>${esc(name(m.id))}</b>: ${esc(memoryDescription(r,b.mode==='shop'&&m.id===b.player))}<br/>Purchases ${r.purchases}; paid ${r.paid} g; declined ${r.rejections}; abandoned ${r.abandoned}; preference ${r.preference}; promotion trust ${r.trust}; exposures ${r.exposures}.</p>`;}).join(''):''}<p>Customer price ceilings remain private.</p>`);return;}
 else if(t.dataset.trade){const row=receipts(b.state).rows.find(r=>r.trade.id===t.dataset.trade) ,tr=row.trade;modal(`<h2>${esc(item(tr.item).name)} · Day ${tr.round}</h2><p>${esc(name(tr.buyer))} bought from ${esc(name(tr.seller))}: ${g(tr.price)} g. Buyer fee ${tr.buyerFee} g; seller fee ${tr.sellerFee} g.</p>${row.profit!==null?`<p>Original FIFO cost ${g(tr.price-tr.sellerFee-row.profit)} g; realized sale profit ${signed(row.profit)} g.</p>`:''}<p>${esc(text(tr.buyerReason.text))}</p><p>${esc(text(tr.sellerReason.text))}</p>`);return;}
 else if(t.id==='archive'){const s=newspaperState(b);modal(Array.from({length:b.state.metrics.length},(_,n)=>editionAt(s,n+1)).map(p=>`<h2>Day ${p.round}</h2>${p.articles.map(a=>`<h3>${esc(text(a.title))}</h3><p>${esc(text(a.body))}</p><small>${esc(text(a.evidence))}</small>${a.quote?`<p>“${esc(a.quote)}” · fictional commentary</p>`:''}`).join('')}`).join('')||'<p>No day settled yet.</p>');return;}
 else if(t.id==='predict'){modal(`<h2>Who will lead realized profit?</h2><select id="prediction-choice">${results(b).map(r=>`<option value="${r.id}">${esc(name(r.id))}</option>`).join('')}</select><button id="save-prediction">Lock prediction</button><p>Session only; no stakes or effect on the economy.</p>`);return;}
 else if(t.id==='save-prediction'){prediction=input('prediction-choice').value;message=`Prediction locked: ${name(prediction)}.`;}
 else if(t.id==='developer'){modal(`<h2>Developer intervention · assisted run</h2><p>Separate from merchant actions. Public and recorded for tomorrow.</p><select id="shock-item">${b.state.manifest.config.items.map(i=>`<option value="${i.id}">${esc(i.name)}</option>`).join('')}</select><button id="shock">Issue one extra copy tomorrow</button>`);return;}
 else if(t.id==='shock'){act(b,{kind:'intervention',intervention:{id:'manual-'+b.actions.length,round:b.state.round+1,kind:'issue',items:[input('shock-item').value],value:1}});message='Developer intervention recorded for tomorrow. This run is marked assisted.';}
 render();
 }catch(error){message=(error         ).message;document.querySelector('.shop-notice') .textContent=message;}});
setInterval(()=>{if(playing&&b.phase!=='complete')advance();},900);
document.addEventListener('keydown',e=>{if((e.target               ).matches('input,textarea,select')||(document.querySelector('#shop-dialog')                     ).open)return;if(e.code==='Space'&&b.mode==='spectate'&&b.phase!=='complete'){e.preventDefault();playing=!playing;render();}if(e.code==='ArrowRight'&&b.phase!=='complete')advance();});
render();
