import { act, campaigns, exportBazaar, importBazaar, merchant, need, nextDay, relationship, reservations, results, settleDay, startBazaar } from './bazaar.js';
import { holdings, isFighter, primaryAsk } from './engine.js';
import { editionAt } from './newspaper.js';
import { download, tradesCsv, metricsCsv } from './exports.js';
let b=startBazaar(),playing=false,follow='',pauseSales=false,prediction='',message='Welcome. Buy wholesale on day one; your owned stock can be sold from the next opening.';
const root=document.querySelector             ('#root') ,esc=(x        )=>String(x??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;'),g=(n       )=>n.toLocaleString('en-US'),item=(id       )=>b.state.manifest.config.items.find(i=>i.id===id) ,name=(id       )=>id==='shop'?'Wholesale stall':merchant(b,id).name;
const icon=(path                 )=>path?`<img src="./assets/${esc(path)}" alt=""/>`:'';
function render(){const s=b.state,a=merchant(b),r=reservations(b),open=b.phase==='decisions',shop=b.mode==='shop',paper=editionAt(s,s.metrics.at(-1)?.round??0),customers=s.agents.filter(isFighter),rivals=s.agents.filter(a=>!isFighter(a));
root.innerHTML=`<div class="shop-shell"><header class="shop-header"><div><span class="eyebrow">LEAGUE ITEM EXCHANGE · STANDALONE FICTIONAL BAZAAR</span><h1>Ten days. One little shop.</h1><p>Buy finite stock. Know your customers. Keep the receipts.</p></div><a href="./?legacy=1">Legacy experiments & full recording tools ↗</a></header><section class="shop-toolbar"><label>Mode<select id="mode"><option value="shop" ${shop?'selected':''}>Run a shop</option><option value="spectate" ${!shop?'selected':''}>Spectate · autonomous</option></select></label><label>Seed<input id="shop-seed" type="number" value="${s.manifest.seed}"/></label><button id="restart">New run</button><strong>Day ${s.round} / 10 · ${b.phase.toUpperCase()}</strong><button id="advance" class="primary" ${b.phase==='complete'?'disabled':''}>${open?'Settle day':'Open next day'}</button>${!shop?`<button id="auto">${playing?'Pause':'Run automatically'}</button>`:''}<button id="export-shop">Export run</button><button id="import-shop">Import / verify replay</button><button id="csv">Trades CSV</button><button id="metrics">Metrics CSV</button><button id="present">Presentation</button></section><p class="shop-notice" role="status">${esc(message)}</p><p class="muted">${s.manifest.interventions.length?'ASSISTED RUN · developer interventions recorded':'Unassisted run'} · ${s.buyerFeeBps/100}% buyer / ${s.sellerFeeBps/100}% seller fee · Advertising paid to a recorded treasury. No future-event information.</p>
<section class="stats">${[['Spendable cash',g(a.cash)+' g','Initial '+g(b.startCash)+' g'],['Reserved bids',g(r.cash)+' g',g(r.available)+' g available'],['Realized trading profit',g(a.profit)+' g','FIFO acquisition costs and trading fees'],['Advertising',g(b.advertising[b.player]??0)+' g','Net realized '+g(a.profit-(b.advertising[b.player]??0))+' g'],['Owned copies',String(holdings(a)),'Unsold stock is not spendable cash']].map(([l,v,t])=>`<div class="stat"><span>${l}</span><strong>${v}</strong><small>${t}</small></div>`).join('')}</section>
<section class="shop-focus"><div><h2>${shop?'Your counter':'The merchant stalls'}</h2><p>${open?'Opening & decisions: all merchant plans share this public snapshot. Sale proceeds cannot fund today’s wholesale bids.':'Settlement receipts: orders expired, reservations released. Review before opening tomorrow.'}</p></div><div><label>Follow<select id="follow"><option value="">All characters</option>${s.agents.map(a=>`<option value="${a.id}" ${follow===a.id?'selected':''}>${esc(a.name)}</option>`).join('')}</select></label><label><input id="pause-sale" type="checkbox" ${pauseSales?'checked':''}/> Pause on customer sale</label><button id="predict">Prediction</button><button id="developer">Developer interventions</button></div></section>
${b.phase==='complete'?endScreen():''}
<section><h2>Recurring customers <small>Finite three-item builds</small></h2><div class="shop-customers">${customers.map(c=>{const id=need(b,c),o=b.offers.find(o=>o.customer===c.id),rel=relationship(b,c.id,b.player),profile=s.manifest.config.archetypes[c.archetype];return `<article class="customer-card ${follow===c.id?'followed':''}"><div class="customer-top">${icon(profile.icon)}<div><h3>${esc(c.name)}</h3><span>${esc(profile.personality .label)}</span></div><button data-inspect="${c.id}">Inspect</button></div><p>${id?`${icon(item(id).icon)} Wants <b>${esc(item(id).name)}</b>`:'✓ Build complete · no further demand'}</p><small>${c.equipped.length}/3 equipped · ${g(c.cash)} g budget · ${rel.purchases} purchases at your shop · preference ${rel.preference} · promotion trust ${rel.trust}</small>${o&&shop&&open?`<div class="customer-offer"><b>Opening offer: ${g(o.price)} g</b><span>${o.status} · ${o.attempts} attempts used</span>${a.inventory[o.item].length?`<input aria-label="Counteroffer for ${esc(c.name)}" id="counter-${c.id}" type="number" min="1" value="${o.price}"/><button data-negotiate="accept" data-customer="${c.id}">Accept</button><button data-negotiate="counter" data-customer="${c.id}">Counter</button><button data-negotiate="reject" data-customer="${c.id}">Reject / release</button>`:'<small>Acquire this item first to negotiate tomorrow.</small>'}</div>`:''}</article>`;}).join('')}</div></section>
<section><h2>Inventory & limited wholesale</h2><div class="shop-batch"><button id="default-list" ${!shop||!open?'disabled':''}>List owned stock at cost + 15%</button><button id="withdraw" ${!shop||!open?'disabled':''}>Withdraw all unreserved listings & bids</button><span>One listed copy per item each day. Edit price to 0 to withdraw. No same-day flipping.</span></div><div class="shop-items">${s.manifest.config.items.map(i=>{const lots=a.inventory[i.id],npc=b.npc.filter(o=>o.item===i.id&&o.side==='ask'),owned=lots.length;return `<article class="shop-item">${icon(i.icon)}<h3>${esc(i.name)}</h3><button data-market="${i.id}">Inspect market</button><p>Wholesale ${g(primaryAsk(s,i))} g · ${s.markets[i.id].stock} copies<br/>Owned ${owned} · FIFO cost ${lots[0]?g(lots[0].cost)+' g':'—'}</p><small>${npc.map(o=>esc(name(o.owner))+' asks '+g(o.price)+' g').join(' · ')||'No rival retail listing'}</small>${shop&&open?`<div><label>Wholesale bid<input id="bid-${i.id}" type="number" min="0" value="${b.bids[i.id]??Math.floor(primaryAsk(s,i)*1.05)}"/></label><button data-bid="${i.id}">Save bid</button>${owned?`<label>Your ask<input id="ask-${i.id}" type="number" min="0" value="${b.listings[i.id]??Math.ceil(lots[0].cost*1.15)}"/></label><button data-list="${i.id}">Save listing</button>`:''}</div>`:''}<small>${b.bids[i.id]?'Bid reserved '+g(b.bids[i.id])+' g':''} ${b.listings[i.id]?'Listed '+g(b.listings[i.id])+' g':''} ${r.copies.has(i.id)?'Negotiated copy reserved':''}</small></article>`;}).join('')}</div></section>
<section class="shop-columns"><div><h2>Paid promotions & economic gossip</h2><p>Separate from factual reporting. Limited reach, two-day duration, ≤10% price influence. Utility, affordability and price caps still apply.</p>${shop&&open?`<label>Owned inventory<select id="ad-item">${s.manifest.config.items.filter(i=>a.inventory[i.id].length).map(i=>`<option value="${i.id}">${esc(i.name)}</option>`).join('')}</select></label>${Object.entries(campaigns).map(([k,c])=>`<button data-ad="${k}">${c.label} · ${c.cost} g</button>`).join('')}<small>Fair-price promise means at or below reference. Breaking that promise reduces trust; prestige advertising makes no price promise.</small>`:''}<div>${b.promotions.map(p=>`<p><b>PAID AD</b> · ${esc(name(p.merchant))} · ${campaigns[p.kind].label} for ${esc(item(p.item).name)} · days ${p.start}–${p.end} · ${p.customers.length} reached · ${p.sales} sales</p>`).join('')||'No promotions purchased yet.'}</div><h3>Rival results · same 12,000 g start</h3>${results(b).map(r=>`<p><button data-inspect="${r.id}">${esc(r.name)}</button> ${g(r.cash)} g cash · ${g(r.realized)} g realized · ${r.advertising} g ads</p>`).join('')}</div><div class="newspaper shop-paper"><span class="eyebrow">FACTUAL REPORTING · THROUGH LAST SETTLED DAY</span><h2>The Runeterra Ledger</h2>${paper.articles.map(p=>`<article><h3>${esc(p.title)}</h3><p>${esc(p.body)}</p><small>${esc(p.evidence)}</small></article>`).join('')}<button id="archive">Edition archive</button></div></section>
<section class="shop-columns"><div><h2>Consequences & decisions</h2>${b.report.map(t=>`<p>${esc(t)}</p>`).join('')}</div><div><h2>Recorded trade receipts</h2>${s.trades.filter(t=>!follow||t.buyer===follow||t.seller===follow).slice(-20).reverse().map(t=>`<button class="shop-receipt" data-trade="${t.id}">Day ${t.round} · ${esc(name(t.buyer))} ← ${esc(name(t.seller))}<br/>${esc(item(t.item).name)} · ${g(t.price)} g · fees ${t.buyerFee+t.sellerFee} g</button>`).join('')||'<p>No matching completed trades yet.</p>'}</div></section><footer>Accounting checked after every action and settlement. Advertising treasury: ${g(b.advertisingTreasury)} g (included in shop treasury). No guaranteed customers or liquidation.</footer></div><dialog id="shop-dialog"><button id="close-shop-dialog">Close</button><div id="shop-dialog-content"></div></dialog>`;
}
function endScreen(){const r=results(b).find(r=>r.id===b.player) ,lots=r.inventory;let pnl                                =[];const costs                        ={};for(const t of b.state.trades){if(t.buyer===b.player)(costs[t.item]??=[]).push(t.price+t.buyerFee);if(t.seller===b.player)pnl.push({trade:t.id,profit:t.price-t.sellerFee-costs[t.item].shift() });}pnl.sort((a,b)=>b.profit-a.profit);return `<section class="shop-ending"><span class="eyebrow">THE SHUTTERS ARE DOWN</span><h2>${r.won?'More cash in the till!':'The shop challenge is over.'}</h2><p>Starting cash ${g(r.starting)} g → ending cash ${g(r.cash)} g. ${r.won?'Challenge achieved.':'Ending spendable cash did not exceed the starting balance.'} Realized trading profit ${g(r.realized)} g; advertising ${r.advertising} g; net realized ${g(r.netRealized)} g.</p><p>Unsold inventory at original cost basis: ${lots.map(l=>`${esc(item(l.item).name)} ×${l.copies}: ${g(l.costBasis)} g`).join(' · ')||'None'}. No liquidation value is assumed.</p>${pnl.length?`<button data-trade="${pnl[0].trade}">Best completed sale: ${g(pnl[0].profit)} g</button><button data-trade="${pnl.at(-1) .trade}">Worst completed sale: ${g(pnl.at(-1) .profit)} g</button>`:'<p>No completed resale deals.</p>'}${prediction?`<p>Prediction: ${esc(name(prediction))} · ${results(b).filter(r=>r.realized===Math.max(...results(b).map(r=>r.realized))).map(r=>esc(r.name)).join(', ')} led realized trading profit.</p>`:''}<details><summary>Your consequential decision timeline</summary>${b.history.filter(h=>b.mode==='spectate'||h.text.includes('your')||h.text.includes('Your shop')).map(h=>`<p>Day ${h.day}: ${esc(h.text)}</p>`).join('')}${b.actions.map(a=>`<p>Day ${a.day} · ${a.kind} ${esc(a.item?item(a.item).name:a.customer?name(a.customer):'')} ${a.price??''}</p>`).join('')}</details></section>`;}
function modal(html       ){playing=false;document.querySelector('#shop-dialog-content') .innerHTML=html;(document.querySelector('#shop-dialog')                     ).showModal();}
function advance(){if(b.phase==='decisions'){const n=b.state.trades.length;settleDay(b);if(pauseSales&&b.state.trades.slice(n).some(t=>t.seller!=='shop'))playing=false;message='Settlement complete. All unused reservations released.';}else if(b.phase==='settlement'){nextDay(b);message='Opening: review needs, wholesale supply, rival asks and your offers.';}if(b.phase==='complete')playing=false;render();}
root.addEventListener('change',e=>{const t=e.target                    ;if(t.id==='follow'){follow=t.value;render();}if(t.id==='pause-sale')pauseSales=t.checked;});
root.addEventListener('click',e=>{const t=(e.target               ).closest('button')                     ;if(!t)return;try{if(t.id==='restart'){playing=false;b=startBazaar(Number((document.querySelector('#shop-seed')                    ).value)>>>0,(document.querySelector('#mode')                     ).value                     );prediction='';message='New ten-day run. Every merchant starts with equal cash.';}
else if(t.id==='advance'){advance();return;}else if(t.id==='auto'){playing=!playing;}else if(t.id==='present'){document.body.classList.toggle('shop-presentation');}
else if(t.dataset.bid)act(b,{kind:'bid',item:t.dataset.bid,price:Number((document.querySelector('#bid-'+t.dataset.bid)                    ).value)});
else if(t.dataset.list)act(b,{kind:'list',item:t.dataset.list,price:Number((document.querySelector('#ask-'+t.dataset.list)                    ).value)});
else if(t.dataset.negotiate)act(b,{kind:t.dataset.negotiate                               ,customer:t.dataset.customer,price:Number((document.querySelector('#counter-'+t.dataset.customer)                    ).value)});
else if(t.dataset.ad)act(b,{kind:'advertise',campaign:t.dataset.ad               ,item:(document.querySelector('#ad-item')                     ).value});
else if(t.id==='default-list'){for(const i of b.state.manifest.config.items.filter(i=>merchant(b).inventory[i.id].length&&!reservations(b).copies.has(i.id)))act(b,{kind:'list',item:i.id,price:Math.ceil(merchant(b).inventory[i.id][0].cost*1.15)});}
else if(t.id==='withdraw'){for(const id of Object.keys(b.bids))act(b,{kind:'bid',item:id,price:0});for(const id of Object.keys(b.listings))act(b,{kind:'list',item:id,price:0});}
else if(t.id==='export-shop')download('bazaar-run.json',exportBazaar(b),'application/json');else if(t.id==='csv')download('bazaar-trades.csv',tradesCsv(b.state),'text/csv');else if(t.id==='metrics')download('bazaar-metrics.csv',metricsCsv(b.state),'text/csv');
else if(t.id==='import-shop'){modal('<h2>Import & recompute replay</h2><textarea id="shop-import" aria-label="Bazaar replay JSON" rows="12"></textarea><button id="verify-shop">Verify pasted replay</button><button id="verify-current">Recompute current run</button>');return;}
else if(t.id==='verify-shop'||t.id==='verify-current'){b=importBazaar(t.id==='verify-current'?exportBazaar(b):(document.querySelector('#shop-import')                       ).value);if(t.id==='verify-shop')prediction='';message='Replay verified: recorded actions recomputed to the same result.';}
else if(t.id==='close-shop-dialog'){(document.querySelector('#shop-dialog')                     ).close();return;}
else if(t.dataset.market){const i=item(t.dataset.market),m=b.state.markets[i.id];modal(`<h2>${esc(i.name)}</h2><p>Reference ${g(i.reference)} g · last executed ${g(m.last)} g ${m.lastRound===null?'(untraded)':`(day ${m.lastRound}; ${m.lastRound<b.state.round?'stale':'latest settlement'})`} · current stock ${m.stock} · manufactured ${m.manufactured}</p><table><thead><tr><th>Day</th><th>Executed average</th><th>Volume</th><th>Stock</th></tr></thead><tbody>${m.history.map(h=>`<tr><td>${h.round}</td><td>${h.price===null?'No trades':g(h.price)+' g'}</td><td>${h.volume}</td><td>${h.stock}</td></tr>`).join('')}</tbody></table><p>No sale or liquidation is implied by a stale price.</p>`);return;}else if(t.dataset.inspect){const a=merchant(b,t.dataset.inspect);modal(`<h2>${esc(a.name)}</h2><p>${g(a.cash)} g cash · ${g(a.profit)} g realized</p><p>Gear: ${a.equipped.map(id=>esc(item(id).name)).join(', ')||'none'}</p><p>Inventory: ${Object.entries(a.inventory).filter(([,l])=>l.length).map(([id,l])=>`${esc(item(id).name)} ×${l.length}, cost basis ${g(l.reduce((n,l)=>n+l.cost,0))} g`).join('; ')||'none'}</p><p>${esc(b.state.manifest.config.story .traders[b.state.agents.filter(a=>!isFighter(a)).findIndex(x=>x.id===a.id)]?.blurb??b.state.manifest.config.archetypes[a.archetype].personality .blurb)}</p><p>Customer price ceilings are private in this scenario.</p>`);return;}
else if(t.dataset.trade){const tr=b.state.trades.find(x=>x.id===t.dataset.trade) ;let cost                 ;const fifo         =[];for(const x of b.state.trades){if(x.item!==tr.item)continue;if(x.buyer===tr.seller)fifo.push(x.price+x.buyerFee);if(x.seller===tr.seller){const basis=fifo.shift();if(x.id===tr.id){cost=basis;break;}}}modal(`<h2>${esc(item(tr.item).name)} · Day ${tr.round}</h2><p>${esc(name(tr.buyer))} bought from ${esc(name(tr.seller))}: ${g(tr.price)} g. Buyer fee ${tr.buyerFee}, seller fee ${tr.sellerFee}.</p>${cost!==undefined?`<p>Original FIFO cost ${g(cost)} g; realized sale profit ${g(tr.price-tr.sellerFee-cost)} g.</p>`:''}<p>${esc(tr.buyerReason.text)}</p><p>${esc(tr.sellerReason.text)}</p>`);return;}
else if(t.id==='archive'){modal(Array.from({length:b.state.metrics.length},(_,n)=>editionAt(b.state,n+1)).map(p=>`<h2>Day ${p.round}</h2>${p.articles.map(a=>`<h3>${esc(a.title)}</h3><p>${esc(a.body)}</p><small>${esc(a.evidence)}</small>`).join('')}`).join('')||'<p>No day settled yet.</p>');return;}
else if(t.id==='predict'){if(b.state.round!==1||b.state.metrics.length)throw Error('Predictions lock after the first settlement.');modal(`<h2>Who will lead realized profit?</h2><select id="prediction-choice">${results(b).map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join('')}</select><button id="save-prediction">Lock prediction</button><p>Session only; no stakes or effect on the economy.</p>`);return;}
else if(t.id==='save-prediction')prediction=(document.querySelector('#prediction-choice')                     ).value;
else if(t.id==='developer'){if(b.phase!=='decisions'||b.state.round===10)throw Error('Developer tools are available during decisions before day ten.');modal(`<h2>Developer intervention · assisted run</h2><p>Separate from normal merchant actions. Public and recorded for tomorrow.</p><select id="shock-item">${b.state.manifest.config.items.map(i=>`<option value="${i.id}">${esc(i.name)}</option>`).join('')}</select><button id="shock">Issue one extra copy tomorrow</button>`);return;}
else if(t.id==='shock')act(b,{kind:'intervention',intervention:{id:'manual-'+b.actions.length,round:b.state.round+1,kind:'issue',items:[(document.querySelector('#shock-item')                     ).value],value:1}});
if(t.id!=='verify-shop'&&t.id!=='verify-current')message=t.dataset.negotiate?b.report.at(-1) :'Decision saved. Review before settlement.';render();}catch(error){message=(error         ).message;const notice=document.querySelector('.shop-notice');if(notice)notice.textContent=message;}});
setInterval(()=>{if(playing)advance();},900);document.addEventListener('keydown',e=>{if((e.target               ).matches('input,textarea,select'))return;if(e.code==='Space'&&b.mode==='spectate'){e.preventDefault();playing=!playing;render();}if(e.code==='ArrowRight'&&b.phase!=='complete')advance();});render();
